### ISSUE TITLE
Question: Syntax for Creating Folders

### ISSUE THREAD

**Issue by spg-craig** [akeeba/s3#16]
I apologize, this isn't an issue per se, I'm hoping you could point me in the right direction to use this awesome script to create a folder within a bucket and or bucket / path (sub-folder)?

**Comment by nikosdion** [comment]
I assume you figured it out? 

For anyone else looking for it, Amazon S3 doesn't actually have the concept of folders. It's just a key-value store. By convention, you can have path-looking keys such as `foo/bar/baz.dat`. When requesting a list of a bucket you can give it a prefix and a separator. The default separator is `/`. The prefix is what we'd call a path in any filesystem context. So if I tell Amazon S3 to list the bucket using the prefix `foo/bar` it will return the `foo/bar/baz.dat` object key. Another corollary of how the directory listing works is that it only returns keys whose prefix matches the given prefix exactly. That is to say, if you ask for a bucket listing with the prefix `foo/bar` you will get `foo/bar/baz.dat` but NOT `foo/bar/example/something.txt` because the latter's prefix is `foo/bar/example` and you are looking for keys with the `foo/bar` prefix. This makes Amazon S3 effectively operate as a filesystem.

So, there is really no concept of "creating a folder". You just create objects ("files") with any prefix ("path") you want and this appears like folders in most S3 browser software, including the one in the Amazon S3 console. If you try to put the object with key `foo/bar/baz/bat/something.txt` you don't need to have any of these "folders" created. The object will be uploaded and Amazon S3 browsers will pretend that there is a root "folder" called `foo` which has a "subfolder" called `bar` which has a "subfolder" called `baz` which has a "subfolder" called `bat` which has a "file" called `something.txt`. The only thing that really exists in S3 is a binary blob object with the key `foo/bar/baz/bat/something.txt`.

I know it is a very weird concept when you first encounter it. Once you wrap your head around the difference between what is stored and how it _appears_ to be accessed everything makes perfect sense, I promise!
