### ISSUE TITLE
Presigned upload URLS

### ISSUE THREAD

**Issue by alexander-zierhut** [akeeba/s3#27]
<details>
<summary>Unrelated</summary>
Hi @nikosdion, love the comments about bloat and glad you wrote this library, so I don't have to import the insane aws sdk. Regarding your Cloudfront costs, maybe Cloudflare R2 could be cheap for you. No egress cost! :)
</details>

There is one feature I am currently missing, which are presigned upload URLs, so a client can directly upload to S3 without going through a backend. Great for i.e. uploading large media files. I have been poking around in the `Signature` Class, but I am not quite sure yet if this is an actually different feature or could simply be merged into the `getAuthenticatedURL` functionality or even simply by adding a few custom headers. Thanks in advance!

Docs for reference: https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html

**Comment by nikosdion** [comment]
I already know about CloudFlare. I prefer the flexibility and stability of CloudFront.

Back to your question. You need to look at https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-authentication-HTTPPOST.html to understand what you need to do. Basically, the pre-signed URL calculates the S3v4 signature of the POST request.

The request **MUST** include a [policy](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html). Pre-signed POST uploads are weird like that.

The signature must be included as an `<input type="hidden" name="x-amz-signature" value="..." />` field. To get its value, create a `\Akeeba\Engine\Postproc\Connector\S3v4\Request` object, setting its headers to the values of the hidden fields of the POST form _except `x-amz-signature` (you must never include the `x-amz-signature` in the request to be signed)_ and the URL of the request being the same as the action of the POST form. 

**IMPORTANT!** Remember to set an `Expires` header; this is necessary for the whole thing to work right.

Then, get the signature with `Signature::getSignatureObject($request, 'v4')->getAuthorizationHeader()`. This string goes into the value of the `x-amz-signature` of your POST form.

Well, at least that's the theory based on the documentation. I've never done that and it is very convoluted. The trickiest part is that you need a policy document. Because of that, this kind of code can never make it into the library. Adding code to abstract Amazon's policy documents is many times over the current library size. For this reason I am closing this issue as "not planned"; I don't want to give anyone the false hope that we might sometime support pre-signed HTTP POST upload URLs.

**Comment by alexander-zierhut** [comment]
Thank you for your response. If I manage to do it with this library I will open a PR, at least for documentation.

**Comment by nikosdion** [comment]
That would be great, thank you!
