### ISSUE TITLE
Support for Digital Ocean Spaces?

### ISSUE THREAD

**Issue by ryandemmer** [akeeba/s3#6]
The Spaces API is apparently interoperable with the Amazon S3 API - https://developers.digitalocean.com/documentation/spaces/#aws-s3-compatibility - so I was hoping that changing to the appropriate endpoint would be enough for use with this library, but alas it is not so, I receive a 403 error when attempting to list a bucket.

Any idea what would be required to make it work with DO Spaces?

**Comment by nikosdion** [comment]
I have not tried using their API but they seem to support Amazon S3 v4 and v2 signatures. Translated from their Python example, using a v4 signature:

```php
$config = new Configuration($accessKey, $secretKey, 'v4', 'nyc3');
$config->setEndpoint('nyc3.digitaloceanspaces.com');
$config->setSSL(true);
$config->setUseLegacyPathStyle(false);
$connector = new Connector($config);
```

The only important bit I see is that the endpoint must always include the region name. With Amazon S3 this is not necessary since we do a bit of magic in the `Request` object and add that ourselves. With custom endpoints you have to specify it yourself. In fact, DO's documentation implies this is necessary when using the official Amazon SDK (boto3) as well.

Alternatively you can use the v2 signature method without a region BUT the endpoint must still include the region name (e.g. `nyc3.digitaloceanspaces.com`, not `digitaloceanspaces.com`).

This is not dissimilar to how S3 works. The major difference is that S3 allows you to list all buckets under your account and their properties, no matter their region, if you query the us-east-1 region. DO does not seem to have such a feature. If you have buckets in different regions you need to set up different endpoints.

I hope that helps!

**Comment by ryandemmer** [comment]
It works with v2 but not v4.

Thanks Nicholas.

**Comment by nikosdion** [comment]
Their v4 implementation looks like it may be using different names for some headers (without an `amz-` prefix). We can't really change that implementation in our code because we've found out some cases where Amazon S3 would fail to understand the signature _unless_ we were using `amz-`-prefixed headers. I'm pretty sure that was a bug with S3 itself but since our canonical implementation is against S3 I just can't change that code.
